mode = "auto"

[git]

[git.config]
email = "semverbot@github.com"
name = "semverbot"

[git.tags]
prefix = "v"
suffix = ""

[semver]
patch = ["fix", "bug"]
minor = ["feature"]
major = ["release"]

[semver.config]
parse-mode = "tolerant"
per-prefix = false

[modes]

[modes.git-branch]
delimiters = "/"

[modes.git-commit]
delimiters = "[]/"
